spring.application.name=photopia-back
spring.datasource.url=jdbc:postgresql://postgresql-photopia.alwaysdata.net:5432/photopia_db
spring.datasource.username=${DB_USER_USERNAME}
spring.datasource.password=${DB_USER_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=never

r2.account-id=${R2_ACCOUNT_ID}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket-name=photopia

jwt.secret=${JWT_SECRET}